apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ts-deployment-part1.yml
 - ts-deployment-part2.yml
 - ts-deployment-part3.yml
 - trainticket-gateway.yaml

patches:
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value: [{ name: harborreg }]
